name: CI/CD
on:
  push:
    branches: [ master ]
    
jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python -m unittest discover tests/
      - name: Run mypy
        run: |
          mypy main.py
  deployment:
    needs: [test_suite]
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 54.157.23.32
          username: github-actions
          key: ${{ secrets.ssh_key }}
          port: 22
          script: |
            rm -rf squiz
            git clone https://github.com/samomatik/squiz.git
            python3.8 -m venv /home/github-actions/squiz/venv
            /home/github-actions/squiz/venv/bin/pip3.8 install -r /home/github-actions/squiz/requirements.txt